flashUtilities +=	Kernel_data.o \
			Kernel_interface.o \
			Kernel_mapParticles.o \
			krn_calculateWeights.o \
			krn_checkBounds.o \
			krn_divideDensity.o \
			krn_findParticles.o \
			krn_getCellWeight.o \
			krn_gridTotals.o \
			krn_initBlocks.o \
			krn_init.o \
			krn_kernel.o \
			krn_makeParticle.o \
			krn_moveParticles.o \
			krn_partTotals.o \
			krn_smoothParticles.o \
			krn_sortParticles.o \
			krn_timestamp.o \
			krn_zeroGridVar.o

Kernel_interface.o: Kernel_data.o
Kernel_mapParticles.o: Kernel_interface.o
krn_calculateWeights.o: Kernel_interface.o
krn_checkBounds.o: Kernel_interface.o
krn_divideDensity.o: Kernel_interface.o
krn_findParticles.o: Kernel_interface.o
krn_getCellWeight.o: Kernel_interface.o
krn_gridTotals.o: Kernel_interface.o
krn_initBlocks.o: Kernel_interface.o
krn_init.o: Kernel_interface.o
krn_kernel.o: Kernel_interface.o
krn_makeParticle.o: Kernel_interface.o
krn_moveParticles.o: Kernel_interface.o
krn_partTotals.o: Kernel_interface.o
krn_smoothParticles.o: Kernel_interface.o
krn_sortParticles.o: Kernel_interface.o
krn_timestamp.o: Kernel_interface.o
krn_zeroGridVar.o: Kernel_interface.o
