
PhotoChem += PhotoChem_data.o \
              PhotoChem_interface.o \
              phch_interface.o \
              phch_calculateRate.o \
              phch_clearPixels.o \
              phch_electronEquilibrium.o \
              phch_evolveChem.o \
              phch_evolveMetal.o \
              phch_evolvePhoto.o \
              phch_findNumIndices.o \
              phch_gasConstant.o \
              phch_healpix.o \
              phch_interpPhoto.o \
              phch_interpMetal.o \
              phch_loadMetal.o \
              phch_loadPhoto.o \
              phch_makeLogIndices.o \
              phch_mapPixels.o \
              phch_readFile.o \
              phch_updateSources.o \
              PhotoChem.o \
              PhotoChem_init.o



