flashUtilities += Smooth_particles.o \
		  smooth_Data.o \
	          smooth_fillGuardCells.o \
		  smooth_Init.o \
		  smooth_Prolong.o \
		  smooth_recordNodeTypeStates.o \
		  smooth_restoreNodeTypes.o \
		  smooth_Restrict.o \
		  smooth_prepareNodes.o

